### ISSUE TITLE
text missing when opening svg file in illustrator

### ISSUE THREAD

**Issue by sqjin** [r-lib/svglite#124]
Hello, when I open .svg file in illustrator CC2019, some text is missing. When importing the file, the illustrator warns that 'clipping will be lost on roundtrip to Tiny'.  Below is a screenshot. Do you have any idea how to get rid of this issue? Thank you! 
![image](https://user-images.githubusercontent.com/32399212/96281828-bd432900-0f8e-11eb-9665-1eecd47aa8f5.png)

**Comment by nx10** [comment]
Can you show an example of missing text?

As for the warning message:

> SVG Tiny is a subset of SVG intended for use with mobile devices such as cell phones. It does not support certain constructs, among them clipping masks. The graphic you are working with contains a clipping mask. The alert is simply telling you that the clipping mask will not survive the trip back to SVG Tiny, if you save it in that format.
[Source](https://community.adobe.com/t5/illustrator/clipping-will-be-lost-on-roundtrip-to-tiny/td-p/1203608?page=1&profile.language=de)

svglite makes extensive use of clipping masks in SVGs. I think you can just press "Don't Show Again" and ignore this warning, unless you intend to work with the SVG Tiny format.

**Comment by sqjin** [comment]
Hi @nx10 , thanks for the prompt response.  I do not want to work with the SVG Tiny format. Can I get rid of this format? Below is my code for saving plot as svg file:
`    svglite(file = "test.svg", width = 5, height = 5)
      visual_circle(prob, vertex.size = vertex.size)
      dev.off()`

A few weeks ago when I used R version 3.5, there is no issue for importing .svg file into illustrator. However, after I changed to R version 3.6 recently, I encounter such issue. I just re-installed svglite from the github, but there is still missing text, e.g., the text associated with light green circle in [this figure](https://www.dropbox.com/s/i85anx7bu7b5c2d/FGF_circle.svg?dl=0)

Thank you!

**Comment by thomasp85** [comment]
Can you please provide a reproducible example if you want me to look into it?

**Comment by sqjin** [comment]
@thomasp85 Thanks! Can you please take a look at this example (https://www.dropbox.com/s/i85anx7bu7b5c2d/FGF_circle.svg?dl=0). When opening it in illustrator, the text associated with light green circle in this figure is missing.   The code I used to save this figure is 
svglite(file = "test.svg", width = 5, height = 5)

 visual_circle(prob, vertex.size = vertex.size) 

dev.off()

**Comment by thomasp85** [comment]
where does the function `visual_circle()` come from? and what is `prob` and `vertex.size`?

a reproducible example means that you provide me with code that I can copy-and-paste into a fresh R session and replicate the issue. Have a look at the reprex package (https://github.com/tidyverse/reprex) for some tools that helps with this :-)
