### ISSUE TITLE
svglite does not play nice with xts

### ISSUE THREAD

**Issue by paessens** [r-lib/svglite#126]
Hi dear Developers,
there seems to be a bug in svglite, hence, we cannot use the compiled svg-image without correction.

test case: [see test-svglite.R, files attached] 

- import times series as xts
- specify filename (*.svg)
- plot, i.e. plot.xts
- first file is test2.svg and this cannot be opened in a viewer 
- firefox shows error 
![Image 15 12 20 at 17 55](https://user-images.githubusercontent.com/7040827/102246228-cb65e500-3efe-11eb-9b60-0c4688490b4c.jpg)

Solution: the first 11 lines must be deleted!

![Untitled 2](https://user-images.githubusercontent.com/7040827/102247152-dcfbbc80-3eff-11eb-89f6-4342dc9facaa.jpg)

![corrected svg](https://user-images.githubusercontent.com/7040827/102247186-eb49d880-3eff-11eb-911f-09a451b99c5e.jpg)

Please could you investigate and remediate?
Many thanks and much appreciated.

Heinrich

[Archive.zip](https://github.com/r-lib/svglite/files/5697333/Archive.zip)

**Comment by paessens** [comment]
sorry I forgot ...
![Untitled 3](https://user-images.githubusercontent.com/7040827/102247689-8b9ffd00-3f00-11eb-95e8-c8f764426933.png)

**Comment by paessens** [comment]
heck ;-)

**Comment by paessens** [comment]
heck ... I forgot ...
![Untitled 3](https://user-images.githubusercontent.com/7040827/102248018-fe10dd00-3f00-11eb-8618-3096fcc134e4.png)

**Comment by thomasp85** [comment]
This seems to be based on the CRAN version of svglite... The dev version includes a lot of rewrites, so can you check if the issue persists there?

**Comment by paessens** [comment]
yes, it's still there
[Screenshot 2021-02-01 at 13.24.26.pdf](https://github.com/r-lib/svglite/files/5903863/Screenshot.2021-02-01.at.13.24.26.pdf)

My function for a corrected svg-file is 

[Screenshot 2021-02-01 at 13.25.40.pdf](https://github.com/r-lib/svglite/files/5903877/Screenshot.2021-02-01.at.13.25.40.pdf)

**Comment by paessens** [comment]
then I have a corrected svg like this


[file2b551127afa2.svg.zip](https://github.com/r-lib/svglite/files/5903908/file2b551127afa2.svg.zip)

**Comment by paessens** [comment]
sorry, I did this not in test

![prod-env-Rstudio](https://user-images.githubusercontent.com/7040827/106462775-d23cbd00-6496-11eb-9e44-823ae8920f1e.png)

**Comment by thomasp85** [comment]
According to that you are still using the CRAN version of svglite?

**Comment by paessens** [comment]
well, this happened. which version is it?

![Untitled 2](https://user-images.githubusercontent.com/7040827/106465049-bdadf400-6499-11eb-8e27-e28d317f7ceb.png)

**Comment by thomasp85** [comment]
You'll need to restart R to have the update take effect

**Comment by thomasp85** [comment]
Also, if it does persist please provide a reproducible example

**Comment by paessens** [comment]
OK, in test, I take the files from above Archive.zip

The CRAN version delivers file, but needs correction, as shown above.
The github version fails to write the file as requested by svglite('test2.svg') in the first step.

![Untitled 3](https://user-images.githubusercontent.com/7040827/106477956-028d5700-64a9-11eb-8975-61423583ad95.png)

**Comment by thomasp85** [comment]
I cannot replicate this. Neither the error message nor any problems with the generated svg... Do you have write access to the location you are working in?

**Comment by paessens** [comment]
Yes i do

**Comment by thomasp85** [comment]
Is xts required to trigger the issue?

**Comment by paessens** [comment]
Yes, no issues with other data types crossed my path so far. I value svg and especially svglite very much since the file sizes can be kept small. That's also the reason why I use svg-buddy to optimize (even more). To keep typography consistent my preferred font (roboto condensed) is embedded, but only once for the dashboard (of 20 or more svg files).

**Comment by thomasp85** [comment]
Is there anything weird about your setup at all? Since I can't replicate any of this and since a graphic device have no concept of which packages are loaded (it only receives low-level instructions such as "draw a line there") this issue seems downright unsolvable unless we can somehow replicate it outside of your computer

**Comment by paessens** [comment]
Not that I know, everythng is fine considering setup on debian10 and macos11.15.7, on both machines the issue arises as you can see above. Let me check this issue on windows later the day.

**Comment by paessens** [comment]
here is testing windows -- same result, i.e. theres two def-tagged sections before the xml and svg tag that should not be there (the same applis to CRAN version)

![Screenshot 2021-02-03 at 03 34 52](https://user-images.githubusercontent.com/7040827/106690035-509d7a00-65d1-11eb-9072-56fecfb17bd9.png)

**Comment by paessens** [comment]
here is the corrected svg file

![Screenshot 2021-02-03 at 03 45 49](https://user-images.githubusercontent.com/7040827/106690658-8000b680-65d2-11eb-8615-a950ebd53b41.png)

**Comment by thomasp85** [comment]
Can you provide a reprex that does not rely on any loaded data

**Comment by paessens** [comment]
here you go -- same issue

![Screenshot 2021-02-03 at 10 07 39](https://user-images.githubusercontent.com/7040827/106723988-fec41680-6607-11eb-9f7c-6212fa397a32.png)

**Comment by paessens** [comment]
![Screenshot 2021-02-03 at 10 14 26](https://user-images.githubusercontent.com/7040827/106724668-c5d87180-6608-11eb-8e3c-fbe163554487.png)

**Comment by thomasp85** [comment]
Please use the reprex package as it ensures that your example is self contained and is not reliant on anything in your R setup. Have a look at https://reprex.tidyverse.org/index.html to familiarise yourself with the package

**Comment by paessens** [comment]
Sorry Thomas, I can't see any benefit from that. I consider the provided examples as simple, reproducible and self contained. The produced image should look like 

![Screenshot 2021-02-03 at 10 20 30](https://user-images.githubusercontent.com/7040827/106726001-39c74980-660a-11eb-8ef2-2559fb219635.png)

and not like 

![Screenshot 2021-02-03 at 10 28 12](https://user-images.githubusercontent.com/7040827/106726407-a0e4fe00-660a-11eb-9464-959295973f04.png)

**Comment by thomasp85** [comment]
I can see your issue now... In the future though, please do not use screen shots of code as it makes it extremely cumbersome for those you wish to help you reproduce your issue

**Comment by paessens** [comment]
here you go:

require(xts)
require(svglite)
sessionInfo()
# estr <- readRDS("estr.rds")
estr <- xts(1:10, Sys.Date()+1:10)
svglite('test2.svg')
plot(estr, main='€STR')
dev.off()

**Comment by paessens** [comment]
sorry I should know what a hashtag means in MD ;-)
