### ISSUE TITLE
Ensure leading spaces are rendered in <text> tags

### ISSUE THREAD

**Issue by hrbrmstr** [r-lib/svglite#131]
This:

![image](https://user-images.githubusercontent.com/509878/108742416-ad6fbe80-7505-11eb-81e4-2e8471f3e49f.png)

has stretched out characters due to leading spaces that R properly calculates `textLength` for 👍🏽 

```xml
<text x='131.01' y='100.03' style='font-size: 11.04px; font-weight: 300; fill: #E1E1E1; font-family: Inter; font-feature-settings: "calt" 1,"tnum" 1,"case" 1,"dlig" 1,"ss01" 1,"kern" 1,"zero" 0,"salt" 0;' textLength='150.57px' lengthAdjust='spacingAndGlyphs'>&lt;- A fairly useless annotation</text>
<text x='131.01' y='111.62' style='font-size: 11.04px; font-weight: 300; fill: #E1E1E1; font-family: Inter; font-feature-settings: "calt" 1,"tnum" 1,"case" 1,"dlig" 1,"ss01" 1,"kern" 1,"zero" 0,"salt" 0;' textLength='157.15px' lengthAdjust='spacingAndGlyphs'>       that uses the custom Inter</text>
<text x='131.01' y='123.21' style='font-size: 11.04px; font-weight: 300; fill: #E1E1E1; font-family: Inter; font-feature-settings: "calt" 1,"tnum" 1,"case" 1,"dlig" 1,"ss01" 1,"kern" 1,"zero" 0,"salt" 0;' textLength='124.20px' lengthAdjust='spacingAndGlyphs'>          variant by default.</text>
```

but SVG renders won't actually render the leading spaces unless they are told not to:

```xml
<text x='131.01' y='111.62' style='white-space: pre; font-size: 11.04px; font-weight: 300; fill: #E1E1E1; font-family: Inter; font-feature-settings: "calt" 1,"tnum" 1,"case" 1,"dlig" 1,"ss01" 1,"kern" 1,"zero" 0,"salt" 0;' textLength='157.15px' lengthAdjust='spacingAndGlyphs'>       that uses the custom Inter</text>
<text x='131.01' y='123.21' style='white-space: pre; font-size: 11.04px; font-weight: 300; fill: #E1E1E1; font-family: Inter; font-feature-settings: "calt" 1,"tnum" 1,"case" 1,"dlig" 1,"ss01" 1,"kern" 1,"zero" 0,"salt" 0;' textLength='124.20px' lengthAdjust='spacingAndGlyphs'>          variant by default.</text>
```

![image](https://user-images.githubusercontent.com/509878/108747172-2a516700-750b-11eb-915a-f36ab2e47ddc.png)

Either a warning or documentation to such effect might be useful or an {svglite} option to have leading `<text>` spaces rendered (i.e. set `white-space: pre;` in the `style` attribute).

I can help do either but wanted to have this up as an issue for discussion.

**Comment by thomasp85** [comment]
I think the right course forward is to simply add `white-space: pre;` in the top-level style block... I was unaware of how svg handled leading spaces, but for svglite to create true R output it needs to honour leading spaces...

You are welcome to do a PR, but I can do it as well
