### ISSUE TITLE
devSVG.cpp:21:10: fatal error: 'png.h' file not found

### ISSUE THREAD

**Issue by brainprint** [r-lib/svglite#133]
Hi and thank you for your package. I have face this error today.

R version 4.0.3 (2020-10-10)
macOS 11.2.1 - Intel
svglite  2.0.0

devSVG.cpp:21:10: fatal error: 'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
make: *** [devSVG.o] Error 1
ERROR: compilation failed for package ‘svglite’

**Comment by hrbrmstr** [comment]
Try running:

```
brew install libpng
```

at a Terminal prompt and recompiling.

**Comment by brainprint** [comment]
Perfect. Thank you very much.

**Comment by ddauber** [comment]
I had the same issue and followed the instructions. It works now. Thanks, @hrbrmstr!

**Comment by joelfishbein** [comment]
At first I got this error:
`bash: brew: command not found`

I installed Homebrew (https://brew.sh/), then called `brew install libpng`, and then was able to install svglite as expected.

**Comment by cattapre** [comment]
Did not work for me. Getting the same error message

**Comment by hrbrmstr** [comment]
you're missing `libpng` in your link path somewhere. this works for everyone who has a proper homebrew or macports setup and the png library installed. these are table stakes for doing dev-based installs.

**Comment by danmackinlay** [comment]
Me neither @cattapre. I wonder if you, like me, have homebrew installed in a non-standard location?

**Comment by danmackinlay** [comment]
Also @cattapre I find that the problem as arisen in version 2.0.0.

So for me this fails, throwing the error you mention:

```r
devtools::install_version("svglite", version = "2.0.0", repos = "http://cran.us.r-project.org")
```

But this works fine: 

```r
devtools::install_version("svglite", version = "1.2.3", repos = "http://cran.us.r-project.org")
```

Can you confirm?

**Comment by C-Iacuaniello** [comment]
Good morning, I am also trying to install svglite and have a similar error.
I am on R version 3.6.1, I have libpng installed and up to date.
I am getting the following error:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/systemfonts/libs/systemfonts.so
  Reason: image not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘svglite’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/svglite’
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘/var/folders/p9/yjdhyd8d6m3b1m185gzz_c8c0000gp/T//RtmpFcjbr3/remotes82be22d1069e/svglite’ had non-zero exit status

**Comment by cattapre** [comment]
> Also @cattapre I find that the problem as arisen in version 2.0.0.
> 
> So for me this fails, throwing the error you mention:
> 
> ```r
> devtools::install_version("svglite", version = "2.0.0", repos = "http://cran.us.r-project.org")
> ```
> 
> But this works fine:
> 
> ```r
> devtools::install_version("svglite", version = "1.2.3", repos = "http://cran.us.r-project.org")
> ```
> 
> Can you confirm?

My issue is gone. The binary provided fixed the problem.

**Comment by imanuelcostigan** [comment]
I too have this issue. Have brew config per default, but running on an Apple Silicon Mac.

**Comment by thomasp85** [comment]
brew behaves differently on silicon and you'll need to alert R to the different location of its libraries

put this in your global .Makevars

```
CFLAGS=-I/opt/homebrew/include
CPPFLAGS=-I/opt/homebrew/include
CXXFLAGS=-I/opt/homebrew/include
CXX11FLAGS=-I/opt/homebrew/include
LDFLAGS=-L/opt/homebrew/lib
```

**Comment by rohilsaraf97** [comment]
Could you please tell me where to find the global .Makevars file on macOS?

**Comment by imanuelcostigan** [comment]
See https://cran.r-project.org/bin/macosx/RMacOSX-FAQ.html#Installation-of-source-packages

**Comment by RuDevelooper** [comment]
> Try running:
> 
> ```
> brew install libpng
> ```
> 

Thank you!
