### ISSUE TITLE
Issue when converting plots that have clip-path on Linux to raster images with 2.0

### ISSUE THREAD

**Issue by jcubic** [r-lib/svglite#135]
I'm not sure if this is the right place to report this. But there is issue with new version of SVGLite that generates svg that then is converted to images using imageMagik or rsvg on GNU/Linux machine. The same issue happen in docker built from rbase image.

I'm attaching the svg and output image. It look like clip-path issue that is not recognized by common GNU/Linux tools to generate raster images from svg.

[bmiComparisonFit_1.svg.gz](https://github.com/r-lib/svglite/files/6090345/bmiComparisonFit_1.svg.gz)

![bmiComparisonFit_1](https://user-images.githubusercontent.com/280241/110113507-7e820400-7db3-11eb-90a1-24e7e5041511.png)

The version before 2.0 works fine, tested on docker when we hardcoded the version.

**Comment by jcubic** [comment]
I was testing clip-path and I've removed all clip-path from the file and the issue remain. I've reported but to Ubuntu

https://bugs.launchpad.net/ubuntu/+bug/1918925

**Comment by thomasp85** [comment]
hmm... I'm not sure what would cause this on the svglite side... Have there been any update on this?
