### ISSUE TITLE
ggplot title is hard to edit by hand in inkscape

### ISSUE THREAD

**Issue by ekernf01** [r-lib/svglite#141]
Hi svglite devs, I'm using svglite `2.0.0.9000` and `ggplot2 3.3.5` on `R 4.0.0`. When I save plots as svg and open them in inkscape, it's hard to edit the text because deleting words causes the rest of the test to  s t r e t c h   o u t  to preserve the size of the box. I don't know if this behavior is desired, but some folks involved with inkscape & ggplot2 encouraged me to report it here. Thanks for taking a look; here's a reprex.

```
library(ggplot2)
ggplot(diamonds) + 
  geom_point(aes(x = cut, y = carat)) + 
  ggtitle("A very long title which I now regret and wish to edit in inkscape or somesuch")
ggsave("~/Desktop/reprex.svg", width = 5, height = 5)
```

Then I open this in inkscape and delete the words after "regret". I use 

```
Inkscape 1.0.2 (1.0.2+r75+1)
    Pango version: 1.40.14
```
.

**Comment by thomasp85** [comment]
You can set `fix_text_size = FALSE` in the device call (or in `ggsave()`)

The reason for the behaviour is that svglite cannot predict exactly how the renderer will display the text and at what width so in order for exact positioning it needs to enforce a certain width - the above setting turns it off
