### ISSUE TITLE
SVGLITE GGPLOT images cannot be read downstream by Python SVGLIB SVG2RLG

### ISSUE THREAD

**Issue by louis-gallo-cigna** [r-lib/svglite#153]
Recently, it seems that GGPLOT SVGLITE output cannot be read downstream by Python REPORTLAB via SVGLIB SVG2RLG. 

I get this error:

'lxml.etree._Element' object has no attribute 'ancestors'

I have SVG images from other sources that reimport into REPORTLAB fine.

I find that if I fiddle with the SVG file produced by SVGLITE by removing the first defs, all works as it should.

REMOVE THIS FROM SVGLITE GENERATED FILE

`<defs>
  <style type='text/css'><![CDATA[
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
  ]]></style>
</defs>`

I have included the SVGLITE generated file.

![myfile](https://user-images.githubusercontent.com/45264234/164327145-29ef06c4-eee6-41f5-a5de-0e6eba6c898d.svg)

I do not want to blame SVGLITE because it may be the downstream Python library that reads it.

Any help is appreciated.

Lou

**Comment by thomasp85** [comment]
My guess is that the Python lib doesn't support CDATA entries, but that is on them :-) There is not much we can do on our end
