### ISSUE TITLE
Pass labs(alt="user-generated text") to alt/desc tag in SVG

### ISSUE THREAD

**Issue by jthomasmock** [r-lib/svglite#154]
`ggplot2` has support for user-generated alt text via `labs()` but this is not passed into the output SVG when `ggsave()` is used.

Given that this `ggplot2` -> `svg` is typically created as inline SVG it would be most appropriate to include both and`aria-labelledby="title"` and a `desc` tag. From my understanding, the `title` would be a very brief summary while the `desc` would be the longer user-generated alt-text.

If it was created as an `<img>` tag it would be more appropriate to use an `alt` and `role` tag.

A good resource at [Web Accessibility Guidelines - SVG](http://web-accessibility.carnegiemuseums.org/code/svg/) or the `<desc>` element on [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc). Also see the [W3 Desc/Title elements](https://www.w3.org/TR/SVG/struct.html#DescriptionAndTitleElements) and [W3 SVG accessibility](https://www.w3.org/TR/2000/NOTE-SVG-access-20000807/#Equivalent)

Tagging @batpigandme to close the loop from our discussion.

**Comment by thomasp85** [comment]
There is unfortunately not any way to pass additional information into the graphic engine in order to support this. If this changes down the line I'd be happy to add support in svglite
