### ISSUE TITLE
svglite does not produce editable text in all use cases (faceted plots, patchwork)

### ISSUE THREAD

**Issue by cycloxslug** [r-lib/svglite#159]
The svglite library does not always retain text in ggplots - see plot 3 export below. If you put two plots together using the patchwork library, the text is converted to outlines and no longer retained as editable text. The same appears to be true if a ggplot is faceted via facet_grid. All text is converted to shapes.

```
set.seed(1)
df <- data.frame(
  gp = factor(rep(letters[1:3], each = 10)),
  y = rnorm(30)
)
ds <- do.call(rbind, lapply(split(df, df$gp), function(d) {
  data.frame(mean = mean(d$y), sd = sd(d$y), gp = d$gp)
}))

p1<-ggplot(df, aes(gp, y)) +
  geom_point() +
  geom_point(data = ds, aes(y = mean), colour = 'red', size = 3)

p2<-ggplot(df, aes(gp, y)) +
  geom_point() +
  geom_point(data = ds, aes(y = mean), colour = 'green', size = 3)

library(patchwork)

p3 <- p1|p2

ggsave(plot = p1, "p1.svg", device = svglite)


ggsave(plot = p3, "p3.svg", device = svglite)
```

**Comment by thomasp85** [comment]
I cannot reproduce this. Your code produce editable text in both cases. There is no code in the svglite library that allows it to render text as outline so I suspect you inadvertently used the `svg()` device
