### ISSUE TITLE
SVG polyline element seems to need fill specification to avoid spurious fill

### ISSUE THREAD

**Issue by robert-dodier** [r-lib/svglite#177]
I am working with svglite 2.1.3 in R 4.4.1 on Ubuntu 16.04.

I am generating SVG files via invocations such as the following:
```
dev.new()
svglite ("tmp7.svg")
plot.new ()
plot.window (xlim = c(0, 2), ylim = c(0, 4)) 
lines ((1:20)/10, ((1:20)/10)**2, col='red')
dev.off()
```
which produces
```
<?xml version='1.0' encoding='UTF-8' ?>
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='720.00pt' height='576.00pt' viewBox='0 0 720.00 576.00'>
<defs>
  <style type='text/css'><![CDATA[
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  ]]></style>
</defs>
<rect width='100%' height='100%' style='stroke: none; fill: #FFFFFF;'/>
<defs>
  <clipPath id='cpMC4wMHw3MjAuMDB8MC4wMHw1NzYuMDA='>
    <rect x='0.00' y='0.00' width='720.00' height='576.00' />
  </clipPath>
</defs>
<g clip-path='url(#cpMC4wMHw3MjAuMDB8MC4wMHw1NzYuMDA=)'>
</g>
<defs>
  <clipPath id='cpNTkuMDR8Njg5Ljc2fDU5LjA0fDUwMi41Ng=='>
    <rect x='59.04' y='59.04' width='630.72' height='443.52' />
  </clipPath>
</defs>
<g clip-path='url(#cpNTkuMDR8Njg5Ljc2fDU5LjA0fDUwMi41Ng==)'>
<polyline points='111.60,485.11 140.80,482.03 170.00,476.89 199.20,469.71 228.40,460.47 257.60,449.17 286.80,435.83 316.00,420.43 345.20,402.97 374.40,383.47 403.60,361.91 432.80,338.29 462.00,312.63 491.20,284.91 520.40,255.13 549.60,223.31 578.80,189.43 608.00,153.49 637.20,115.51 666.40,75.47 ' style='stroke-width: 0.75; stroke: #FF0000;' />
</g>
</svg>
```
That figure is displayed as expected -- just solitary red curve -- when I view it with a web browser, but when I try to view it with a stand-alone viewer (namely Ristretto), it shows a black blotch on it, and, more distressingly, `pandoc` produces a PDF with that same blotch when I include the SVG.

The issue appears to be that the polyline is being filled; see e.g. https://stackoverflow.com/questions/10213155/unclosed-svg-path-appears-to-be-closed for a discussion about someone else who bumped into the problem in a different context.

I find that I can patch the SVG to say `style='stroke-width: 0.75; stroke: #FF0000; fill: none;` and then the figure is displayed as expected.

I see that at the outset, the SVG contains `fill: none;` but I guess that declaration is superseded by the one in the polyline itself?

Can svglite emit the appropriate `fill` declaration in the style attached to `polyline`? I suppose it should match whatever is declared at the outset.

Is there already a flag to tell svglite to emit the appropriate `fill` in `polyline`? I looked at all the documentation I could find and didn't see anything about it.

**Comment by thomasp85** [comment]
Can I get you to try with the dev version of svglite?

**Comment by robert-dodier** [comment]
Thanks for the update, I'll be glad to try it. By what means should I obtain and make use of the development version of svglite? Sorry for the bother, I just want to avoid any gyrations trying to search for the necessary steps.

**Comment by robert-dodier** [comment]
@thomasp85 I've updated the installed svglite following the instructions by trevorld. Looks like the output still has the same bug -- when I try the example stated in my initial comment, the generated file tmp7.svg still isn't displayed correctly. 

For the record here's the difference between the output generated by the previous svglite version and the version installed via `install.packages`.

```
--- /tmp/tmp7.svg	2024-10-24 23:40:59.436676676 -0700
+++ ./tmp7.svg	2024-10-24 23:44:07.382316330 -0700
@@ -1,5 +1,6 @@
 <?xml version='1.0' encoding='UTF-8' ?>
-<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='svglite' width='720.00pt' height='576.00pt' viewBox='0 0 720.00 576.00'>
+<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='720.00pt' height='576.00pt' viewBox='0 0 720.00 576.00'>
+<g class='svglite'>
 <defs>
   <style type='text/css'><![CDATA[
     .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
@@ -30,4 +31,5 @@
 <g clip-path='url(#cpNTkuMDR8Njg5Ljc2fDU5LjA0fDUwMi41Ng==)'>
 <polyline points='111.60,485.11 140.80,482.03 170.00,476.89 199.20,469.71 228.40,460.47 257.60,449.17 286.80,435.83 316.00,420.43 345.20,402.97 374.40,383.47 403.60,361.91 432.80,338.29 462.00,312.63 491.20,284.91 520.40,255.13 549.60,223.31 578.80,189.43 608.00,153.49 637.20,115.51 666.40,75.47 ' style='stroke-width: 0.75; stroke: #FF0000;' />
 </g>
+</g>
 </svg>
```
As you can see, the `polyline` is still lacking `fill: none`.

**Comment by thomasp85** [comment]
I don't intend to put `fill: none` in every polyline element. Ristretto is obviously bugged, but I had hoped I could make it work better by moving the class from the parent svg element to a child g element.

Pandoc had the same issue but that should be fixed in newer versions.

I'd suggest changing your svg viewer as svglite is not going to make changes that can severely increase file size in order to work well with a non-compliant viewer

**Comment by robert-dodier** [comment]
Sorry, I didn't understand that it's a ristretto bug. I'll try their newest version. I certainly would not ask you to make poorly-motivated changes to svglite to compensate for a bug somewhere else.

**Comment by thomasp85** [comment]
All good -- the pandoc thing has been annoying which is why there were some merit to changing things in svglite, but thankfully they accepted a PR to fix their bug
