### ISSUE TITLE
Linking after compiling with `-O0` fails

### ISSUE THREAD

**Issue by jimhester** [r-lib/svglite#83]
I get a `Symbol not found: __ZN12CairoContextD1Ev` error when trying to load the shared library. After demangling this is `CairoContext::~CairoContext()` defined in gdtools. So this package needs to link to the gdtools library to work in this scenario. Likely the destructor is being inlined normally so you don't see this error.

From [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Linking-to-other-packages) trying to link to a dynamic library in another package is problematic and not portable, it is instead suggested that the package provide a static library to link to instead.

<details>
<summary>Full error message</summary>

```
Loading svglite
Re-compiling svglite
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL '/Users/jhester/pkg/svglite'  \
  --library='/var/folders/dt/r5s12t392tb5sk181j3gs4zw0000gn/T//RtmpfZDpmG/devtools_install_20c73acd9f58' --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec  \
  --no-multiarch --no-test-load --preclean

* installing *source* package ‘svglite’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/jhester/Library/R/3.3/library/Rcpp/include" -I"/Users/jhester/Library/R/3.3/library/gdtools/include" -I"/Users/jhester/Library/R/3.3/library/BH/include"   -fPIC  -O0 -g -c RcppExports.cpp -o RcppExports.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/jhester/Library/R/3.3/library/Rcpp/include" -I"/Users/jhester/Library/R/3.3/library/gdtools/include" -I"/Users/jhester/Library/R/3.3/library/BH/include"   -fPIC  -O0 -g -c devSVG.cpp -o devSVG.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o svglite.so RcppExports.o devSVG.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /private/var/folders/dt/r5s12t392tb5sk181j3gs4zw0000gn/T/RtmpfZDpmG/devtools_install_20c73acd9f58/svglite/libs
* DONE (svglite)
Error in dyn.load(dllfile) :
  unable to load shared object '/Users/jhester/pkg/svglite/src/svglite.so':
  dlopen(/Users/jhester/pkg/svglite/src/svglite.so, 6): Symbol not found: __ZN12CairoContextD1Ev
  Referenced from: /Users/jhester/pkg/svglite/src/svglite.so
  Expected in: flat namespace
 in /Users/jhester/pkg/svglite/src/svglite.so
```
</details>

**Comment by lionel-** [comment]
hmm... the CairoContext is created by calling an exported gdtools function, which returns an `XPtr` to an object created by the gdtools package. Thus IIRC the methods should be called from the gdtools side. Also the header that provides the declaration for `XPtr<CairoContext>` does not have any definition anyway, so it couldn't be a matter of inlining.

I don't understand how this issue happened. Is it possible this is somehow a compiler mismatch thing?

**Comment by jimhester** [comment]
Did you try setting `CXXFLAGS = -O0` in your `.R/Makevars` to see if you get the same behavior?

**Comment by lionel-** [comment]
yup it loads without error. It compiles with `-O3 -O0` but the latter flag has priority right?

**Comment by lionel-** [comment]
> the latter flag has priority right

recompiled with `CXXFLAGS= -O0` instead of `CXXFLAGS+= -O0` and it loads fine as well.

**Comment by jimhester** [comment]
I am using the following compiler version

```
clang++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Setting the compiler flags to use gcc 4.9 and re-compiling all the deps from source it does work.
```r
deps <- devtools::dev_package_deps(dep=TRUE)
remove.packages(deps$package)
install.packages(deps$package, type = "source")
```
But doing the same with clang and `-O0` has unchanged results.

**Comment by lionel-** [comment]
I have the same clang, that's strange.

**Comment by lionel-** [comment]
I'm stumbling against this issue. With `clang -O2` it works but with `clang -O0` it's including the destructor symbol in the library. It's very strange that it would do that, here is the definition exported by gdtools:

```c++
class CairoContext {
  struct CairoContext_;
  CairoContext_* cairo_;
  typedef std::map<std::string, cairo_font_face_t*> fontCache;

public:
  CairoContext();
  ~CairoContext();

  void cacheFont(fontCache& cache, std::string& key, std::string fontfile, int fontindex);
  void cacheSystemFont(std::string& key, std::string& fontname, bool bold, bool italic);
  void setFont(std::string fontname = "sans", double fontsize = 12,
               bool bold = false, bool italic = false,
               std::string fontfile = "");
  void setUserFont(std::string& fontname, double fontsize,
                   bool bold, bool italic, std::string& fontfile);
  void setSystemFont(std::string& fontname, double fontsize,
                     bool bold, bool italic);

  FontMetric getExtents(std::string x);
  bool validateGlyphs(std::string x);

};

typedef Rcpp::XPtr<CairoContext> XPtrCairoContext;
```

Maybe a bug in clang?
