### ISSUE TITLE
R v3.4: svglite fails to install

### ISSUE THREAD

**Issue by chrisalcantara** [r-lib/svglite#85]
Hello! 

I'm trying to download svglite but keep running into this issue: 
`ERROR: dependency ‘gdtools’ is not available for package ‘svglite’`. 

I've raised the issue with the gdtool people because installing that library results in a compiling error.

I'm currently running R 3.4. Maybe it's a compatibility issue?

**Comment by lionel-** [comment]
This is probably because the gdtools package was not built for your OS and that R version at that time. Please reopen if that's still an issue.
