### ISSUE TITLE
Extremely low resolution of a raster part of svg

### ISSUE THREAD

**Issue by VPetukhov** [r-lib/svglite#86]
I'm trying to create svg with a raster part. When I just plot it in R or save it as png, everything is going well. Using svg device also works fine. However, svglite saves it with terrible resolution of the raster part. Here is the code, which produces a nested ggplot with a raster part (it uses Cairo, grDevices and grid).

    Cairo::Cairo(type='png', width=1200, height=1200, dpi=300, units='px', bg="transparent")
    ggplot2::qplot(1:100)
    grob <- grid::rasterGrob(grDevices::dev.capture())
    grDevices::dev.off()

    svglite::svglite('plot.svg', width=4, height=4)
    print(ggplot2::qplot(1:1000) + ggplot2::annotation_custom(grob))
    grDevices::dev.off()

**Comment by herbstk** [comment]
This problem still persists. Is there any solution?

**Comment by thomasp85** [comment]
This will be fixed by #104

**Comment by herbstk** [comment]
I tried it and it worked perfectly. Thanks for great effort.
