### ISSUE TITLE
Make <style> element optional, or add an id?

### ISSUE THREAD

**Issue by benbell95** [r-lib/svglite#91]
Currently in svglite, a svg file is created using the `<style>` element to set global styles for line, polyline, path, rect, circle.

While this works well for single svg files, if using multiple inline svgs on the same html page, the style element can override the styling for all other svgs on that page with undesirable results.

Is it possible to add an argument to the svglite function to make the use of `<style>` optional? something like `style=TRUE/FALSE?`

Alternatively, could id tags be added to the style code so it is only applied to that image? Perhaps an option to specify the id? e.g. `id="svg1"`

As a workaround, i enclose the svgs in my html pages within `<div>` tags and alter the style defs so styling is not applied globally e.g.

```
<div id="svg1">
<svg>
<defs>
  <style type='text/css'>
    #svg1 line, #svg1 polyline, #svg1 path, #svg1 rect, #svg1 circle {
      fill: none;
      stroke: #000000;
    }
  </style>
</defs>
svg here
</svg>
</div>
```

**Comment by jcubic** [comment]
This is anoying you can't have SVG that is not shiny plot on the page because of this. CSS is applied to whole page. So you can have SVG logo on shiny app.
