### ISSUE TITLE
Missing edges in svg file for some point characters when background color is set

### ISSUE THREAD

**Issue by andrewmarx** [r-lib/svglite#92]
I'm trying to save some plots in the svg format, but edges are not being outputted for some symbols in the svg file when a background color is used. They show up fine in the plot pane and png outputs. Here is an example of the issue:
![compare](https://user-images.githubusercontent.com/13956617/46290349-96f1f280-c559-11e8-9920-a526e07a5c5d.png)

Potentially useful info:
- Completely removed R and associated packages and did a fresh install of 3.4.4. 
- Tested on 2 Ubuntu based operating systems (16.04LTS and 18.04LTS)
- Attached plots (in zip file because svg files cannot be attached)

``` r
library("svglite")

dat <- data.frame(x = c(1,2,3,4,5),
                  y = c(1,2,3,4,5),
                  sym = c(21,22,23,24,25))

svglite("~/plot.svg")
plot(dat$x, dat$y, pch = dat$sym, width = 6, cex = 5)
dev.off()


svglite("~/plot2.svg")
plot(dat$x, dat$y, pch = dat$sym, width = 6, bg = "yellow", cex = 5)
dev.off()
```
[plots.zip](https://github.com/r-lib/svglite/files/2434027/plots.zip)

**Comment by tshalev** [comment]
Andrew; did you ever solve this issue?

**Comment by thomasp85** [comment]
I can no longer reproduce this issue, so it seems to have been resolved. Please reopen if you still see it
